добавлено Fullscreen API
ArkanoidTeam/theGame pull request #22
Opened 2024-06-06 19:32 UTC by TvojaMamaLama

2024-06-06 20:31 UTC, Valzet approved these changes

2024-06-07 02:36 UTC, Brodyagados approved these changes

2024-06-07 08:53 UTC, Akopyants approved these changes

2024-06-07 11:04 UTC, kate-lozovaya requested changes
Оставила пару комментов. Призывай к ревью, как посмотришь

2024-06-07 11:04 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenButton/FullscreenButton.tsx
> +    if (!document.fullscreenElement) {
[Предложение]
Выражения без отрицания читаются проще. Здесь условие `if else` для отрицания. Было бы хорошо поменять их местами, сначала сделать `if(document.fullscreenElement)`

2024-06-07 11:04 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenButton/FullscreenButton.tsx
> +  const onClick = () => {
[Исправление]
Оберни в `useCalback`, чтобы функция не пересоздавалась на ререндеры

2024-06-07 11:04 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenButton/FullscreenButton.tsx
> +        })
[Предложение]
Функция для отображения ошибки повторяется. Можно ее вынести за компонент и использовать в обоих `catch`

2024-06-08 10:47 UTC, kate-lozovaya approved these changes
Функцию `onCatch` нужно вынести за компонент, чтобы она не перресоздавалась на ререндер. Вынеси её, пожалуйста, но блокировать этим тебя не буду, поставлю апрув

2024-06-08 10:47 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenButton/FullscreenButton.tsx
> +  }
[Исправление]
Функция не зависит от компонента, поэтому ее можно вынести за него. Сейчас на каждый рендер компонента функция будет создаваться заново

2024-06-08 20:29 UTC, merged